export { Header } from './Header';
export { Footer } from './Footer';
export { ActionAnimes } from './ActionAnimes';
export { AdventureAnimes } from './AdventureAnimes';
export { ComedyAnimes } from './ComedyAnimes';
export { ScrollToTop } from './ScrollToTop';
export { Card } from './Card';
export { ActionCards } from './ActionCards';
export { TopAnimes } from './TopAnimes';